beerhunter/beers/urls.py
from django.urls import path

from . import views


app_name = "beer"
urlpatterns = [
    path(
        route='',
        view=views.BeerListView.as_view(),
        name='BeerList'
    ),
    path(
        route='search/',
        view=views.Search,
        name="Search"
    ),
    path(
        route='add/',
        view=views.BeerCreateView.as_view(),
        name='add'
    ),
    path(
        route='<slug:slug>/',
        view=views.BeerDetailView.as_view(),
        name='BeerDetail'
    ),
    path(
        route='<int:beer_id>/vote',
        view=views.CreateVote.as_view(),
        name='CreateVote'
    ),
    path(
        route='<int:beer_id>/vote/<int:pk>',
        view=views.UpdateVote.as_view(),
        name='UpdateVote'
    ),
]

beerhunter/hops/urls.py
from django.urls import path

from . import views


app_name = "hops"
urlpatterns = [
    path(
        route='',
        view=views.HopListView.as_view(),
        name='HopList'
    ),
    path(
        route='<slug:slug>/',
        view=views.HopDetailView.as_view(),
        name='HopDetail'
    )
]

beerhunter/users/urls.py
from django.urls import path

from beerhunter.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView


urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("beerhunter.my_syte.urls", namespace="site")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("beerhunter.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'beers/',
        include('beerhunter.beers.urls', namespace='beers')
    ),
    path(
        'breweries/',
        include('beerhunter.breweries.urls', namespace='breweries')
    ),
    path(
        'hops/',
        include('beerhunter.hops.urls', namespace='hops')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beerhunter/breweries/models.py
import os
from uuid import uuid4
from django.db import models
from django.urls import reverse
from django.utils.timezone import now as timezone_now

from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from django_countries.fields import CountryField
from django.utils.translation import gettext as _

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


def brewery_directory_path_with_uuid(instance, filename):
    now = timezone_now()
    extension = os.path.splitext(filename)[1]
    extension = extension.lower()
    uuid_for_url = uuid4()
    return f"{now:%Y/%m}/breweries/{uuid_for_url}{instance.pk}{extension}"


class Brewery(TimeStampedModel):
    title = models.CharField(_('Title of brewery'), max_length=255)
    slug = AutoSlugField(
        "Brewery Slug",
        unique=True,
        always_update=False,
        populate_from='title'
    )
    country_of_origin = CountryField(
        "Country of Origin", blank=True
    )

    image = models.ImageField(
        upload_to=brewery_directory_path_with_uuid,
        default='images/default/fermentation.png',
        null=True,
        blank=True
    )

    icon = ImageSpecField(
        source='image',
        processors=[ResizeToFill(100, 100)],
        format='PNG',
        options={'quality': 60}
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("breweries:BreweryDetail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Brewery"
        verbose_name_plural = "Breweries"

beerhunter/beers/forms.py
from django import forms
from django.contrib.auth import get_user_model
# from django.core.exceptions import ValidationError

from .models import Beer, Vote


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    beer = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Beer.objects.all(),
        disabled=True,
    )

    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect(attrs={'class': 'custom-input'}),
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = (
            'value', 'user', 'beer',
        )

beerhunter/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

beerhunter/beers/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Beer, Vote, BeerComment
from .forms import VoteForm


class BeerListView(ListView):
    paginate_by = 10
    # model = Beer
    queryset = Beer.objects.all_with_related_instances_and_score()

    context_object_name = 'beer_list'

    ordering = ['-score']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['total_beer_list'] = Beer.objects.all()
        return context


class BeerDetailView(DetailView):
    queryset = Beer.objects.all_with_related_instances_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            #   beer_comment = BeerComment(
            #       beer=self.object,
            #       author=self.request.user
            #   )

            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                beer=self.object,
                user=self.request.user
            )

            if vote.id:
                vote_form_url = reverse(
                    'beer:UpdateVote',
                    kwargs={
                        'beer_id': vote.beer.id,
                        'pk': vote.id
                    }
                )
            else:
                vote_form_url = (
                    reverse(
                        'beer:CreateVote',
                        kwargs={
                            'beer_id': self.object.id
                            })
                )
            vote_form = VoteForm(instance=vote)
            #   beer_comment_form = BeerCommentForm(instance=beer_comment)
            ctx['vote'] = vote
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
            #   ctx['beer_comment_form'] = beer_comment_form
        return ctx


class BeerCreateView(LoginRequiredMixin, CreateView):
    model = Beer
    template_name = "beers/beer_form.html"

    fields = [
        'title',
        'style',
        'description',
        'image',
        'brewery',
        'hops',
        'og',
        'abv',
        'ibu'
    ]

    def form_valid(self, form):
        form.instance.hunter = self.request.user
        return super().form_valid(form)


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['beer'] = self.kwargs['beer_id']
        return initial

    def get_success_url(self):
        beer_slug = self.object.beer.slug
        try:
            return reverse(
                'beer:BeerDetail',
                kwargs={
                    'slug': beer_slug})
        except:
            raise ValidationError("Oooops")

    def render_to_response(self, context, **response_kwargs):
        beer_id = context['object'].id
        beer_detail_url = reverse(
            'beer:BeerDetail',
            kwargs={'pk': beer_id})
        return redirect(
            to=beer_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another '
                'users vote'
                )
        return vote

    def get_success_url(self):
        beer_slug = self.object.beer.slug
        return reverse(
            'beer:BeerDetail',
            kwargs={'slug': beer_slug})

    def render_to_response(self, context, **response_kwargs):
        beer_id = context['object'].id
        beer_detail_url = reverse(
            'beer:BeerDetail',
            kwargs={'pk': beer_id})
        return redirect(
            to=beer_detail_url)


def Search(request):
    if request.method == 'POST':
        queryset = Beer.objects.all_with_related_instances_and_score()

        for i in queryset:
            print(i.title)
        search_item = request.POST['query'].lower()
        print(f'We are looking for {search_item}')
        if not search_item:
            return render(request, 'beers/search_result.html')
        search_result = [item for item in queryset if search_item in item.title.lower()]
        return render(request, 'beers/search_result.html', {
            'entries': search_result
        })
    else:
        return render(request, 'beers/search_result.html')

beerhunter/breweries/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models.aggregates import Sum, Max

from .models import Brewery
from beerhunter.beers.models import Beer


class BreweryListView(ListView):
    model = Brewery
    queryset = Brewery.objects.annotate(rating=Sum('brewered__vote__value'))

    context_object_name = "brewery_list"

    #   def get_context_data(self, **kwargs):
    #       ctx = super().get_context_data(**kwargs)
    #       #   all_beers = Beer.objects.values('brewery__name').annotate(total_rating=Sum('vote__value'))
    #       # ctx['total_rating'] = Beer.objects.values('brewery__name').annotate(total_rating=Sum('vote__value'))
    #       # brewery_with_rating = Brewery.objects.values('title').annotate(most_rated=Max('brewered__vote__value'))
    #       brewery_with_rating = Brewery.objects.all().annotate(
    #           most_rated=Beer.objects.all_with_related_instances_and_score().order_by('-score')
    #          )
    #       rating = Beer.objects.all_with_related_instances_and_score().order_by('-score')[0]
    #       print(f'We have for all beers {brewery_with_rating}')
    #       # print(f'Rating for {brewery_with_rating[5]} is {brewery_with_rating[5]}')
    #       return ctx


class BreweryDetailView(DetailView):
    model = Brewery

    def get_context_data(self, **kwargs):
        print(self)
        ctx = super().get_context_data(**kwargs)
        print('initial Brewery ctx is, ', ctx)
        qs_beers = Beer.objects.all_with_related_instances_and_score()
        print('qs_beers are, ', qs_beers)
        brewery_beers = qs_beers.filter(brewery=ctx['brewery'])
        brewery_rating = 0
        for item in brewery_beers:
            if not item.score:
                item.score = 0
            brewery_rating += item.score
        # brewery_rating = brewery_rating / len(brewery_beers)

        ctx['connected_beers'] = brewery_beers
        ctx['rating'] = brewery_rating
        print('Final Brewery ctx is, ', ctx)
        return ctx


class BreweryCreateView(LoginRequiredMixin, CreateView):
    model = Brewery
    template_name = "breweries/brewery_form.html"

    fields = [
        'title',
        'country_of_origin'
    ]

beerhunter/hops/views.py
from django.views.generic import ListView, DetailView

from .models import Hop


class HopListView(ListView):
    # model = Hop
    queryset = Hop.objects.all_with_related_instances_and_score()
    template_name = "hops/hop_list.html"

    ordering = ['-score']


class HopDetailView(DetailView):
    model = Hop
    template_name = "hops/hop_detail.html"

beerhunter/my_syte/views.py
# from django.shortcuts import render
from django.views.generic import TemplateView
from django.db.models import Max, Count

from beerhunter.beers.models import Beer
from beerhunter.hops.models import Hop

# from beerhunter.beers.models import Beer


class HomePageView(TemplateView):
    template_name = "my_syte/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        qs = Beer.objects.all_with_related_instances_and_score()

        top_rating = qs.aggregate(Max('score'))
        top_beer = qs.filter(score=top_rating['score__max'])

        top_ibu = qs.aggregate(Max('ibu'))
        top_ibu_beer = qs.filter(ibu=top_ibu['ibu__max'])

        qs_hop = Hop.objects.annotate(count_beers=Count('brewed_beers'))
        qs_hop_max = qs_hop.aggregate(Max('count_beers'))
        top_hop = qs_hop.filter(count_beers=qs_hop_max['count_beers__max'])

        context["max_score"] = top_rating['score__max']
        context["top_beer"] = top_beer
        context["top_ibu"] = top_ibu['ibu__max']
        context["top_ibu_beer"] = top_ibu_beer
        context["qs_hop_max"] = qs_hop_max['count_beers__max']
        context["top_hop"] = top_hop
        return context

beerhunter/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from beerhunter.beers.models import Beer

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print('Context is: ', context)
        print(f"User id is {context['user'].id}")
        print(f"User permissions are {context['user'].user_permissions.all()}")
        user_beers = Beer.objects.all_with_related_instances_and_score()
        # user_beers = user_beers.filter(hunter=self.request.user.id)
        user_beers = user_beers.filter(hunter=context['user'].id)
        user_beers = user_beers.order_by('-score')

        total_score = 0
        for beer in user_beers:
            if beer.score:
                total_score += beer.score

        context["user_beers"] = user_beers
        context["total_score"] = total_score
        context["total_count"] = user_beers.count()
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = [
        "name",
        "bio",
        ]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        storage = messages.get_messages(self.request)
        for message in storage:
            print(message)
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

beerhunter/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
      {% if object.bio %}
        <p>{{ object.bio|linebreaksbr }}</p>
      {% endif %}
    </div>
  </div>
    <ul>
  {% for beer in connect %}
    <li><a href="{{ beer.get_absolute_url }}">{{ beer }}</a></li>
  {% endfor %}
  </ul>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->

</div>

<p>Welcome {{ user }}.</p>
  <div class="card-deck">
    <div class="card border-light bg-light mb-3" style="max-width: 18rem;">
      <h5 class="card-header">Your status</h5>
      <div class="card-body">
        <p class="card-text">Noob</p>
      </div>
    </div>
    <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
      <div class="card-header">Header</div>
      <div class="card-body">
        <p class="card-text">Some</p>
      </div>
    </div>
  </div>
  {% if not total_count %}
      <h3>You added no beer yet. Just do it!</h3>
  {% else %}
      <h3>You added {{ total_count }} beers with total score {{ total_score }}.</h3>
  {% endif %}
  <div class="row">
      {% for beer in user_beers %}
          <div class="card col-sm-6">
              <!--<img src="{{beer.image.url}}" class="card-img-top" alt="{{ beer }}">-->
              <div class="card-body">
                  {% if beer.version %}
                      <h5 class="card-title"><a href="{{ beer.get_absolute_url }}">{{ beer.title_for_render }} - {{ beer.version }}</a> <span class="badge badge-secondary">Total score: {{ beer.score }}</span></h5>
                  {% else %}
                      <h5 class="card-title"><a href="{{ beer.get_absolute_url }}">{{ beer.title_for_render }}</a> <span class="badge badge-secondary">Total score: {{ beer.score }}</span></h5>
                  {% endif %}   
                  {{ beer.brewery }}
                  <div class="row mb-1">
                      <div class="col-sm-2">OG: <span class="font-weight-bold">{{ beer.og }}%</span></div>
                      <div class="col-sm-2">ABV: <span class="font-weight-bold">{{ beer.abv }}%</span></div>
                      <div class="col-sm-2">IBU: <span class="font-weight-bold">{{ beer.ibu }}</span></div>
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
{% else %}
  {% if not total_count %}
    <p>This user added no beer yet.</p>
  {% else %}
    <p>This user added {{ total_count }} beer{% if total_count > 1 %}s{% endif %} with total score {{ total_score }}.</p>
  {% endif %}
  <div class="row">
        {% for beer in user_beers %}
            <div class="card col-sm-6">
                <!--<img src="{{beer.image.url}}" class="card-img-top" alt="{{ beer }}">-->
                <div class="card-body">
                    {% if beer.version %}
                        <h5 class="card-title"><a href="{{ beer.get_absolute_url }}">{{ beer.title_for_render }} - {{ beer.version }}</a> <span class="badge badge-secondary">Total score: {{ beer.score }}</span></h5>
                    {% else %}
                        <h5 class="card-title"><a href="{{ beer.get_absolute_url }}">{{ beer.title_for_render }}</a> <span class="badge badge-secondary">Total score: {{ beer.score }}</span></h5>
                    {% endif %}   
                    {{ beer.brewery }}
                    <div class="row mb-1">
                        <div class="col-sm-2">OG: <span class="font-weight-bold">{{ beer.og }}%</span></div>
                        <div class="col-sm-2">ABV: <span class="font-weight-bold">{{ beer.abv }}%</span></div>
                        <div class="col-sm-2">IBU: <span class="font-weight-bold">{{ beer.ibu }}</span></div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endif %}
{% endblock content %}

beerhunter/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}