beerhunter/beers/urls.py
from django.urls import path

from . import views


app_name = "beer"
urlpatterns = [
    path(
        route='',
        view=views.BeerListView.as_view(),
        name='BeerList'
    ),
    path(
        route='search/',
        view=views.Search,
        name="Search"
    ),
    path(
        route='add/',
        view=views.BeerCreateView.as_view(),
        name='add'
    ),
    path(
        route='<slug:slug>/',
        view=views.BeerDetailView.as_view(),
        name='BeerDetail'
    ),
    path(
        route='<int:beer_id>/vote',
        view=views.CreateVote.as_view(),
        name='CreateVote'
    ),
    path(
        route='<int:beer_id>/vote/<int:pk>',
        view=views.UpdateVote.as_view(),
        name='UpdateVote'
    ),
]

beerhunter/breweries/urls.py
from django.urls import path

from . import views


app_name = "brewery"
urlpatterns = [
    path(
        route='',
        view=views.BreweryListView.as_view(),
        name='BreweryList'
    ),
    path(
        route='add/',
        view=views.BreweryCreateView.as_view(),
        name='add'
    ),
    path(
        route='<slug:slug>/',
        view=views.BreweryDetailView.as_view(),
        name='BreweryDetail'
    ),
]

beerhunter/hops/urls.py
from django.urls import path

from . import views


app_name = "hops"
urlpatterns = [
    path(
        route='',
        view=views.HopListView.as_view(),
        name='HopList'
    ),
    path(
        route='<slug:slug>/',
        view=views.HopDetailView.as_view(),
        name='HopDetail'
    )
]

beerhunter/users/urls.py
from django.urls import path

from beerhunter.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView


urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", include("beerhunter.my_syte.urls", namespace="site")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("beerhunter.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'beers/',
        include('beerhunter.beers.urls', namespace='beers')
    ),
    path(
        'breweries/',
        include('beerhunter.breweries.urls', namespace='breweries')
    ),
    path(
        'hops/',
        include('beerhunter.hops.urls', namespace='hops')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

beerhunter/my_syte/models.py
from django.db import models

# Create your models here.

beerhunter/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, TextField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Beerhunter.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    bio = TextField("Bio", blank=True)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

beerhunter/beers/forms.py
from django import forms
from django.contrib.auth import get_user_model
# from django.core.exceptions import ValidationError

from .models import Beer, Vote


class VoteForm(forms.ModelForm):

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    beer = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Beer.objects.all(),
        disabled=True,
    )

    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect(attrs={'class': 'custom-input'}),
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = (
            'value', 'user', 'beer',
        )

beerhunter/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

beerhunter/beers/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import Beer, Vote, BeerComment
from .forms import VoteForm


class BeerListView(ListView):
    paginate_by = 10
    # model = Beer
    queryset = Beer.objects.all_with_related_instances_and_score()

    context_object_name = 'beer_list'

    ordering = ['-score']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['total_beer_list'] = Beer.objects.all()
        return context


class BeerDetailView(DetailView):
    queryset = Beer.objects.all_with_related_instances_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            #   beer_comment = BeerComment(
            #       beer=self.object,
            #       author=self.request.user
            #   )

            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                beer=self.object,
                user=self.request.user
            )

            if vote.id:
                vote_form_url = reverse(
                    'beer:UpdateVote',
                    kwargs={
                        'beer_id': vote.beer.id,
                        'pk': vote.id
                    }
                )
            else:
                vote_form_url = (
                    reverse(
                        'beer:CreateVote',
                        kwargs={
                            'beer_id': self.object.id
                            })
                )
            vote_form = VoteForm(instance=vote)
            #   beer_comment_form = BeerCommentForm(instance=beer_comment)
            ctx['vote'] = vote
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
            #   ctx['beer_comment_form'] = beer_comment_form
        return ctx


class BeerCreateView(LoginRequiredMixin, CreateView):
    model = Beer
    template_name = "beers/beer_form.html"

    fields = [
        'title',
        'style',
        'description',
        'image',
        'brewery',
        'hops',
        'og',
        'abv',
        'ibu'
    ]

    def form_valid(self, form):
        form.instance.hunter = self.request.user
        return super().form_valid(form)


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['beer'] = self.kwargs['beer_id']
        return initial

    def get_success_url(self):
        beer_slug = self.object.beer.slug
        try:
            return reverse(
                'beer:BeerDetail',
                kwargs={
                    'slug': beer_slug})
        except:
            raise ValidationError("Oooops")

    def render_to_response(self, context, **response_kwargs):
        beer_id = context['object'].id
        beer_detail_url = reverse(
            'beer:BeerDetail',
            kwargs={'pk': beer_id})
        return redirect(
            to=beer_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another '
                'users vote'
                )
        return vote

    def get_success_url(self):
        beer_slug = self.object.beer.slug
        return reverse(
            'beer:BeerDetail',
            kwargs={'slug': beer_slug})

    def render_to_response(self, context, **response_kwargs):
        beer_id = context['object'].id
        beer_detail_url = reverse(
            'beer:BeerDetail',
            kwargs={'pk': beer_id})
        return redirect(
            to=beer_detail_url)


def Search(request):
    if request.method == 'POST':
        queryset = Beer.objects.all_with_related_instances_and_score()

        for i in queryset:
            print(i.title)
        search_item = request.POST['query'].lower()
        print(f'We are looking for {search_item}')
        if not search_item:
            return render(request, 'beers/search_result.html')
        search_result = [item for item in queryset if search_item in item.title.lower()]
        return render(request, 'beers/search_result.html', {
            'entries': search_result
        })
    else:
        return render(request, 'beers/search_result.html')

beerhunter/breweries/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models.aggregates import Sum, Max

from .models import Brewery
from beerhunter.beers.models import Beer


class BreweryListView(ListView):
    model = Brewery
    queryset = Brewery.objects.annotate(rating=Sum('brewered__vote__value'))

    context_object_name = "brewery_list"

    #   def get_context_data(self, **kwargs):
    #       ctx = super().get_context_data(**kwargs)
    #       #   all_beers = Beer.objects.values('brewery__name').annotate(total_rating=Sum('vote__value'))
    #       # ctx['total_rating'] = Beer.objects.values('brewery__name').annotate(total_rating=Sum('vote__value'))
    #       # brewery_with_rating = Brewery.objects.values('title').annotate(most_rated=Max('brewered__vote__value'))
    #       brewery_with_rating = Brewery.objects.all().annotate(
    #           most_rated=Beer.objects.all_with_related_instances_and_score().order_by('-score')
    #          )
    #       rating = Beer.objects.all_with_related_instances_and_score().order_by('-score')[0]
    #       print(f'We have for all beers {brewery_with_rating}')
    #       # print(f'Rating for {brewery_with_rating[5]} is {brewery_with_rating[5]}')
    #       return ctx


class BreweryDetailView(DetailView):
    model = Brewery

    def get_context_data(self, **kwargs):
        print(self)
        ctx = super().get_context_data(**kwargs)
        print('initial Brewery ctx is, ', ctx)
        qs_beers = Beer.objects.all_with_related_instances_and_score()
        print('qs_beers are, ', qs_beers)
        brewery_beers = qs_beers.filter(brewery=ctx['brewery'])
        brewery_rating = 0
        for item in brewery_beers:
            if not item.score:
                item.score = 0
            brewery_rating += item.score
        # brewery_rating = brewery_rating / len(brewery_beers)

        ctx['connected_beers'] = brewery_beers
        ctx['rating'] = brewery_rating
        print('Final Brewery ctx is, ', ctx)
        return ctx


class BreweryCreateView(LoginRequiredMixin, CreateView):
    model = Brewery
    template_name = "breweries/brewery_form.html"

    fields = [
        'title',
        'country_of_origin'
    ]

beerhunter/hops/views.py
from django.views.generic import ListView, DetailView

from .models import Hop


class HopListView(ListView):
    # model = Hop
    queryset = Hop.objects.all_with_related_instances_and_score()
    template_name = "hops/hop_list.html"

    ordering = ['-score']


class HopDetailView(DetailView):
    model = Hop
    template_name = "hops/hop_detail.html"

beerhunter/my_syte/views.py
# from django.shortcuts import render
from django.views.generic import TemplateView
from django.db.models import Max, Count

from beerhunter.beers.models import Beer
from beerhunter.hops.models import Hop

# from beerhunter.beers.models import Beer


class HomePageView(TemplateView):
    template_name = "my_syte/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        qs = Beer.objects.all_with_related_instances_and_score()

        top_rating = qs.aggregate(Max('score'))
        top_beer = qs.filter(score=top_rating['score__max'])

        top_ibu = qs.aggregate(Max('ibu'))
        top_ibu_beer = qs.filter(ibu=top_ibu['ibu__max'])

        qs_hop = Hop.objects.annotate(count_beers=Count('brewed_beers'))
        qs_hop_max = qs_hop.aggregate(Max('count_beers'))
        top_hop = qs_hop.filter(count_beers=qs_hop_max['count_beers__max'])

        context["max_score"] = top_rating['score__max']
        context["top_beer"] = top_beer
        context["top_ibu"] = top_ibu['ibu__max']
        context["top_ibu_beer"] = top_ibu_beer
        context["qs_hop_max"] = qs_hop_max['count_beers__max']
        context["top_hop"] = top_hop
        return context

beerhunter/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from beerhunter.beers.models import Beer

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print('Context is: ', context)
        print(f"User id is {context['user'].id}")
        print(f"User permissions are {context['user'].user_permissions.all()}")
        user_beers = Beer.objects.all_with_related_instances_and_score()
        # user_beers = user_beers.filter(hunter=self.request.user.id)
        user_beers = user_beers.filter(hunter=context['user'].id)
        user_beers = user_beers.order_by('-score')

        total_score = 0
        for beer in user_beers:
            if beer.score:
                total_score += beer.score

        context["user_beers"] = user_beers
        context["total_score"] = total_score
        context["total_count"] = user_beers.count()
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = [
        "name",
        "bio",
        ]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        storage = messages.get_messages(self.request)
        for message in storage:
            print(message)
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

beerhunter/templates/beers/beer_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ object.title }} - {{ block.super }}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-2 align-self-center text-center">
		<a href="{{ object.image.url }}" target="_blank">
			<img src="{{ object.image.url }}" class="img-fluid" alt="{{ object.title }}">
		</a>
		</div>
		<div class="col-6">
			<h1>
				{{ object.title_for_render }}
			</h1>
			<h6>
				Hunted by: <a href="{{ object.hunter.get_absolute_url }}">{{ object.hunter }}</a>
			</h6>
			{% if object.brewery %}
				<p class="h6">
					Brewed by: <a href="{% url 'brewery:BreweryDetail' slug=object.brewery.slug %}">{{ object.brewery }}</a> (<span class="text-muted">{{ object.brewery.country_of_origin.name }}</span>)
				</p>
			{% else %}
				<p class="h6">
					Brewed by: Unknown master</a>
				</p>
			{% endif %}
			<p class="h6">
			Style: {{ object.style }}
			</p>
			<ul class="list-group list-group-horizontal">
				<li class="list-group-item"><span class="badge badge-success">OG — {{ object.og }}%</span></li>
				<li class="list-group-item"><span class="badge badge-success">ABV — {{ object.abv }}%</span></li>
				<li class="list-group-item"><span class="badge badge-success">IBU — {{object.ibu}}</span></li>
			</ul>
			{% if object.description %}
				<p>
					{{ object.description|linebreaksbr }}
				</p>
			{% endif %}
			<!--
			{% for comment in object.comments.all %}
				{{ comment.title }}
				{{ comment.body }}
			{% endfor %}-->
		</div>
		<div class="col-4">
			<div>
				<h2>
					Score: {{ object.score|default_if_none:"TBD" }}
				</h2>
				Your last vote is: {% if vote.value == 1 %} UP {% elif vote.value == -1 %} DOWN {% else %} None {% endif %}
			</div>
			{% if vote_form %}
				<form method="post" action="{{ vote_form_url }}" id="voteForm">
					{% csrf_token %}
					{% for vote in vote_form.value %}
						<label class="btn btn-block btn-primary" style="cursor: pointer" for="{{ vote.id_for_label }}">
							{{ vote.choice_label }}
							{{ vote.tag }}
						</label>
						<!--<div class="form-check btn btn-primary">
						{{ vote }}
						</div>-->
					{% endfor %}
					{{ vote_form.beer }}
					{{ vote_form.user }}
					<!--<button class="btn btn-primary">Vote</button>-->
				</form>
			{% else %}
				<p>LogIn to vote for this beer</p>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-8">
			<h3>
			Used hops:
			</h3>
		  <ul class="list-group list-group-horizontal">
			{% for hop in object.hops.all %}
				<li class="list-group-item"><a href="{{ hop.get_absolute_url }}">{{ hop }}</a></li>
			{% empty %}
				<li class="list-group-item">Hops are unknown.</li>
			{% endfor %}
		  </ul>
		</div>
	</div>
	{% for comment in object.comments.all %}
		<div class="media">
			<div class="media-body">
				<h5 class="mt-0">{{ comment.title }}</h5>
				{{ comment.body }}
				{{ comment.created }}
			</div>
		</div>
	{% endfor %}
	{% if beer_comment_form %}
	Add Comment:
		<form method="post" action="{% url 'beer:BeerComment' slug=object.slug %}">
			{% csrf_token %}
			{{ beer_comment_form.as_p }}
			<button class="btn btn-primary">Comment</button>
		</form>
	{% endif %}
{% endblock %}

beerhunter/templates/beers/beer_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Beer{% endblock title %}

{% block content %}
<h1>Add Beer</h1>
<form method="post" enctype="multipart/form-data" action="{% url 'beers:add' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock content %}

beerhunter/templates/beers/beer_list.html
{% extends 'base.html' %}

{% block title %}
	All The Beers
{% endblock %}

{% block content %}
			<h1>All the beers {{total_beer_list.count}}</h1>
			<ul class="list-group col">
			{% for beer in beer_list %}
					<li class="custom-list-bg row mt-3 pt-2 pb-2">
						<div class="col-5" style="max-width: 100px">
							<img src="{{ beer.image_icon.url }}" class="img-fluid" alt="{{ beer }}">
						</div>
						<div class="col-4">
							{% if beer.version %}
								<a href="{{ beer.get_absolute_url }}">
									<h4 class="mb-1">
										{{ beer|upper }}
									</h4>
									<p class="h6">
										{{ beer.version }}
									</p>
								</a>
							{% else %}
								<a href="{{ beer.get_absolute_url }}">
									<h4>
										{{ beer|upper }}
									</h4>
								</a>
							{% endif %}
							<div class="mt-1">Style: <span class="font-weight-bold">{{ beer.style }}</span></div>
							<div class="mt-1">Brewed by: <span class="font-weight-bold"><a href="{% url 'breweries:BreweryDetail' slug=beer.brewery.slug %}">{{ beer.brewery }}</a></span></div>
							<div class="row mt-1">
								<div class="col">OG: <span class="font-weight-bold">{{ beer.og }}%</span></div>
								<div class="col">ABV: <span class="font-weight-bold">{{ beer.abv }}%</span></div>
								<div class="col">IBU: <span class="font-weight-bold">{{ beer.ibu }}</span></div>
							</div>
						</div>
						<div class="col-4">
							<div class="mt-1">
								Total score: {{ beer.score|default_if_none:"No votes yet" }}
							</div>
							<div class="mt-1">Hops: 
							{% if beer.hops.count > 0 %}
								<ul class="custom-hops-range">
								{% for hop in beer.hops.all %}
										<li>{{ hop }}</li>
								{% endfor %}
								</ul>
							{% else %}
									<span class="font-weight-bold">hops are unknown</span>
							{% endif %}
							</div>
						</div>
					</li>
    		{% endfor %}
			</ul>
			{% if is_paginated %}
				<nav>
					<ul class="pagination">
						<li class="page-item">
							<a href="{% url 'beer:BeerList' %}?page=1" class="page-link">
								First
							</a>
						</li>
						{% if page_obj.has_previous %}
							<li class="page-item">
								<a href="{% url 'beer:BeerList' %}?page={{ page_obj.previous_page_number }}" class="page-link">
									{{ page_obj.previous_page_number }}
								</a>
							</li>
						{% endif %}
						<li class="page-item active">
							<a href="{% url 'beer:BeerList' %}?page={{ page_obj.number }}" class="page-link">
								{{ page_obj.number }}
							</a>
						</li>
						{% if page_obj.has_next %}
							<li class="page-item">
								<a href="{% url 'beer:BeerList' %}?page={{ page_obj.next_page_number }}" class="page-link">
									{{ page_obj.next_page_number }}
								</a>
							</li>
						{% endif %}
						<li class="page-item">
							<a href="{% url 'beer:BeerList' %}?page=last" class="page-link">
								Last
							</a>
						</li>
					</ul>
				</nav>
			{% endif %}

{% endblock %}

beerhunter/templates/beers/search_result.html
{% extends 'base.html' %}

{% block title %}
    Search results
{% endblock title %}

{% block content %}
    <h1>
        Search Results
    </h1>
    {% if entries %}
        <ul>
            {% for entry in entries %}
            <li><a href='{{entry.get_absolute_url}}'>{{ entry.title_for_render }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        No results
    {% endif %}
{% endblock content %}